MyBlog/urls.py
from django.urls import path

from . import views
app_name = 'MyBlog'
urlpatterns = [
    path('', views.index, name='index'),
    path('blog/', views.Blog, name='Blog'),
    path('loadblog', views.loadblog, name='loadblog'),
    path('admin/menushow/', views.menushow, name='menushow'),
    path('admin/', views.admin, name='admin'),
    path('admin/login/', views.login, name='login'),
    path('admin/console/', views.console, name='console'),
    path('message/', views.message, name='message'),
    path('loadmessage/', views.loadmessage, name='loadmessage'),
    path('submitmessage/', views.submitmessage, name='submitmessage'),
    path('picture/', views.picture, name='picture'),
    path('archive/', views.archive, name='archive'),
    path('like/', views.like, name='like'),
    path('search/', views.search, name='search'),
    path('replylike/', views.replylike, name='replylike'),
    path('about/', views.about, name='about'),
    path('test/', views.test, name='test'),
    path('details/<int:id>', views.details, name='details'),
    path('weblink/', views.weblink, name='weblink'),
    path('picdetails/<int:id>', views.picdetails, name='picdetails'),
    path('types/<int:type>', views.types, name='types'),
    path('category/<int:type>', views.category, name='category'),
    path('imgtypes/<str:type>', views.imgtypes, name='imgtypes'),
    path('commentdata/', views.commentdata, name='commentdata'),
    path('commenttocommentdata/', views.commenttocommentdata, name='commenttocommentdata'),
    path('commenttoreplydata/', views.commenttoreplydata, name='commenttoreplydata'),
    path('loadcommentdata/', views.loadcommentdata, name='loadcommentdata'),
    path('loadarchivedata/', views.loadarchivedata, name='loadarchivedata'),
    path('replydata/', views.replydata, name='replydata'),
    path('replytomessage/', views.replytomessage, name='replytomessage'),
    path('replytoreply/', views.replytoreply, name='replytoreply'),
    path('admin/Top/', views.Top, name='Top'),
    path('admin/upload_ajax/', views.upload_ajax, name='upload_ajax'),
    path('admin/editblog/', views.editblog, name='editblog'),
    path('admin/deleteblog/', views.deleteblog, name='deleteblog'),
    path('admin/Blogsdata/', views.Blogsdata, name='Blogsdata'),
    path('admin/BlogEdit/', views.BlogEdit, name='BlogEdit'),
    path('admin/PicEdit/', views.PicEdit, name='PicEdit'),
    path('admin/PicUploads/', views.PicUploads, name='PicUploads'),
    path('admin/PictureManage/', views.PictureManage, name='PictureManage'),
    path('admin/PicDetailManage/<int:id>', views.PicDetailManage, name='PicDetailManage'),
    path('admin/setWrap/', views.setWrap, name='setWrap'),
    path('admin/userinfo/<int:userid>/', views.userinfo, name='userinfo'),
    path('admin/password/<int:userid>/', views.password, name='password'),
    # path('admin/password/<int:userid>/', views.password, name='password'),



]

MyBlogWeb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', include('MyBlog.urls')),
    path("favicon.ico", RedirectView.as_view(url='static/favicon.ico')),
    path('adminht/', admin.site.urls),
    path('ueditor/', include('DjangoUeditor.urls' )),


]

MyBlog/models.py
from django.db import connection, models
from django.db.models.fields.files import ImageFieldFile
from PIL import Image
from MyBlogWeb.settings import MEDIA_ROOT
import os, datetime, uuid
import re
from DjangoUeditor.models import UEditorField


class BlogManager(models.Manager):
    def blogSet(self):
        cursor = connection.cursor()
        cursor.execute("""
            SELECT *
            FROM Blog
            """)
        return [row for row in cursor.fetchall()]

class Blog(models.Model):
    id = models.AutoField(db_column='id', primary_key=True)
    title = models.CharField(db_column='Title', max_length=50, blank=True, null=True)  # Field name made lowercase.
    abstract=models.CharField(db_column='abstract', max_length=300, blank=True, null=True)
    createdate = models.DateTimeField(db_column='createdate', blank=True, null=True)  # Field name made lowercase.
    modifydate=models.DateTimeField(db_column='modifydate', blank=True, null=True)
    author = models.CharField(db_column='Author', max_length=50, blank=True, null=True)  # Field name made lowercase.
    blogcontent = UEditorField(db_column='blogcontent',verbose_name='内容',width=600, height=300, toolbars="full", imagePath="images/upload/%(datetime)s_%(rnd)s.%(extname)s", filePath="file/upload/%(datetime)s_%(rnd)s.%(extname)s", upload_settings={"imageMaxSize":1204000},
             settings={},command=None,blank=True)  #
    hit = models.IntegerField(db_column='hit', blank=True, null=True)
    isTop = models.IntegerField(db_column='isTop', blank=True, null=True)
    isorg = models.IntegerField(db_column='isorg', blank=True, null=True)
    type = models.IntegerField(db_column='Type',blank=True, null=True)
    imgTitle = models.CharField(db_column='imgTitle', max_length=50, blank=True, null=True)  # Field name made lowercase.
    Category = models.CharField(db_column='Category', max_length=50, blank=True,null=True)  # Field name made lowercase.
    year = models.CharField(db_column='year', max_length=4, blank=True,
                                null=True)  # Field name made lowercase.
    month = models.CharField(db_column='month', max_length=2, blank=True,
                                null=True)  # Field name made lowercase.
    day = models.CharField(db_column='day', max_length=2, blank=True,
                                null=True)  # Field name made lowercase.
    blog_blogtype = models.ManyToManyField(to="BlogType",
                                     through="BlogTypeRelation",
                                     through_fields=("Blog", "BlogType"))
    blog_CategoryToBlog = models.ManyToManyField(to="Category",
                                           through="CategoryToBlog",
                                           through_fields=("Blog", "Category"))
    objects = models.Manager()
    blog_objects = BlogManager()

    def __str__(self):
        dr = re.compile(r'<[^>]+>',re.S)
        dd = dr.sub('', self.blogcontent)
        if len(dd)>500:
            return '{0}...'.format(dd[0:499])
        else:
            return '{0}...'.format(dd)

    class Meta:
        managed = False
        db_table = 'Blog'

class UserManager(models.Manager):
    def userSet(self):
        cursor = connection.cursor()
        cursor.execute("""
            SELECT *
            FROM Users
            """)
        return [row for row in cursor.fetchall()]

class Users(models.Model):
    userid = models.AutoField(db_column='userid', primary_key=True)  # Field name made lowercase.
    useraccount = models.CharField(db_column='useraccount', max_length=50, blank=True,
                                   null=True)  # Field name made lowercase.
    userpassword = models.CharField(db_column='userpassword', max_length=50, blank=True,
                                    null=True)  # Field name made lowercase.
    username = models.CharField(db_column='username', max_length=200, blank=True,
                                null=True)  # Field name made lowercase.
    website = models.CharField(db_column='website', max_length=50, blank=True, null=True)  # Field name made lowercase.
    type = models.IntegerField(db_column='type', blank=True, null=True)
    email = models.CharField(db_column='email', max_length=200, blank=True, null=True)  # Field name made lowercase.
    userpic = models.CharField(db_column='userpic', max_length=50, blank=True, null=True)  # Field name made lowercase.
    objects = models.Manager()
    user_objects = UserManager()

    class Meta:
        managed = False
        db_table = 'Users'

class BlogTypeManager(models.Manager):
    def blogtypeSet(self):
        cursor = connection.cursor()
        cursor.execute("""
            SELECT *
            FROM BlogType
            """)
        return [row for row in cursor.fetchall()]

class BlogType(models.Model):
    id = models.AutoField(db_column='id', primary_key=True)
    TypeName = models.CharField(db_column='TypeName', max_length=50, blank=True, null=True)  # Field name made lowercase.
    category=models.IntegerField(db_column='category',blank=True, null=True)
    objects = models.Manager()
    blogtype_objects = BlogTypeManager()
    blogtype_blog= models.ManyToManyField(to="Blog",
                                           through="BlogTypeRelation",
                                           through_fields=("BlogType", "Blog"))
    pictype_pic = models.ManyToManyField(to="PicManage",
                                           through="PicTypeRelation",
                                           through_fields=("type", "pictureManage"))
    class Meta:
        managed = False
        db_table = 'BlogType'

class BlogTypeRelation(models.Model):
    id = models.AutoField(db_column='id', primary_key=True)
    Blog = models.ForeignKey(to="Blog",to_field="id",on_delete=models.CASCADE)
    BlogType = models.ForeignKey(to="BlogType",to_field="id",on_delete=models.CASCADE)

    class Meta:
        managed = False
        db_table = 'BlogTypeRelation'
        unique_together=("Blog","BlogType")

class PicTypeRelation(models.Model):
    id = models.AutoField(db_column='id', primary_key=True)
    pictureManage = models.ForeignKey(to="PicManage",to_field="id",on_delete=models.CASCADE)
    type = models.ForeignKey(to="BlogType",to_field="id",on_delete=models.CASCADE)
    # objects = models.Manager()
    # blogtyperelation_objects = BlogTypeRelationManager()

    class Meta:
        managed = False
        db_table = 'PicTypeRelation'
        unique_together=("pictureManage","type")

class PictureManager(models.Manager):
    def pictureSet(self):
        cursor = connection.cursor()
        cursor.execute("""
            SELECT *
            FROM BlogType
            """)
        return [row for row in cursor.fetchall()]

class Picture(models.Model):
    id = models.AutoField(db_column='id', primary_key=True)
    pic = models.ForeignKey(to="PicManage", to_field="id", on_delete=models.CASCADE)
    picdesc = models.CharField(db_column='picdesc', max_length=200, blank=True, null=True)  # Field name made lowercase.
    url = models.CharField(db_column='url',max_length=50, blank=True)  # Field name made lowercase.
    objects = models.Manager()
    picture_objects = PictureManager()

    class Meta:
        managed = False
        db_table = 'Picture'

class PicManageManager(models.Manager):
    def picManagetureSet(self):
        cursor = connection.cursor()
        cursor.execute("""
            SELECT *
            FROM PicManage
            """)
        return [row for row in cursor.fetchall()]

# 创建原始图片名称
def generate_filename(instance, filename):
    """
    安全考虑，生成随机文件名
    """
    directory_name = datetime.datetime.now().strftime('upload/imgs/%Y/%m')
    filename = uuid.uuid4().hex + os.path.splitext(filename)[-1]
    return os.path.join(directory_name, filename)

# 创建缩略图名称
def generate_filename_thumb(instance, filename):
    directory_name = datetime.datetime.now().strftime('upload/thumb/%Y/%m')
    filename = uuid.uuid4().hex + os.path.splitext(filename)[-1]
    return os.path.join(directory_name, filename)

# 制作缩略图

UPLOAD_ROOT = generate_filename
THUMB_ROOT = "upload/thumb/" # 这个是最终的缩略图要保存的路径
def make_thumb(path, size = 800):
    pixbuf = Image.open(path)
    width, height = pixbuf.size

    if width > size:
        delta = width / size
        height = int(height / delta)
        pixbuf.thumbnail((size, height), Image.ANTIALIAS)
        return pixbuf



class PicManage(models.Model):
    id = models.AutoField(db_column='id', primary_key=True)
    title = models.CharField(db_column='title', max_length=50, blank=True, null=True)  # Field name made lowercase.
    picdesc = models.CharField(db_column='picdesc', max_length=200, blank=True, null=True)  # Field name made lowercase.
    # 商品图片
    img = models.ImageField(upload_to=generate_filename, null=True)
    # 商品缩略图
    imgthumb = models.ImageField(upload_to=generate_filename_thumb, null=True)
    # url = models.CharField(db_column='url', max_length=50, blank=True, null=True)  # Field name made lowercase.
    author = models.CharField(db_column='author', max_length=50, blank=True, null=True)  # Field name made lowercase.
    createdate = models.DateTimeField(db_column='createdate', blank=True, null=True)  # Field name made lowercase.
    modifydate = models.DateTimeField(db_column='modifydate',  blank=True, null=True)  # Field name made lowercase.
    # type = models.IntegerField(db_column='type',blank=True, null=True)  # Field name made lowercase.
    pic_pictype = models.ManyToManyField(to="BlogType",
                                           through="PicTypeRelation",
                                           through_fields=("pictureManage", "type"))
    objects = models.Manager()
    picmanage_objects = PicManageManager()

    class Meta:
        managed = False
        db_table = 'PicManage'

    def save(self):
        super(PicManage, self).save()  # 将上传的图片先保存一下，否则报错

MyBlog/templates/MyBlog/Blog.html
{% extends 'MyBlog/base.html' %}
{% load static %}
{% block title%}
    <title>花花与风的博文</title>
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'common/css/iconfont.css' %}">
{% endblock %}
{% block nav %}
<div class="nav" id="nav">
 <div class="menu-btn">
      <div class="menu"></div>
    </div>
    <div class="item">
        <a class="navpic" href="../"><img src="{% static 'common/imgs/logo.png' %}"></a>
        <ul class="nav-horizontal">
            <li class="nav-item  layui-this"><a href="../blog">博客</a></li>
            <li class="nav-item"><a href="../weblink">友情链接</a></li>
            <li class="nav-item"><a href="../archive">归档</a></li>
            <li class="nav-item"><a href="../message">留言</a></li>
            <li class="nav-item"><a href="../about">关于</a></li>
        </ul>
        <ul class="nav-tree">
            <li class="nav-item  layui-this"><a href="../blog">博客</a></li>
            <li class="nav-item"><a href="../weblink">友情链接</a></li>
            <li class="nav-item"><a href="../archive">归档</a></li>
            <li class="nav-item"><a href="../message">留言</a></li>
            <li class="nav-item"><a href="../about">关于</a></li>
        </ul>
    </div>
</div>
{% endblock %}
{% block container %}
    <div class="layui-col-md85">
        <div class="content" >
            <ul id="flow"></ul>
        </div>
    </div>
    <div id="right" class="layui-col-md35" >
        <div class="content-sapce-15">
            <div class="layui-col-md12 ">
                <div class="layui-card">
                    <div class="layui-card-header">
                        <i class="layui-icon layui-icon-search"></i>
                        <span>搜索</span>
                    </div>
                    <div class="layui-card-body search-border">
                        <form method="post">
                            {% csrf_token %}
                            <div class="search-con">
                                <input class="layui-input" name="key" id="key" placeholder="搜索...">
                                <button class="layui-icon layui-icon-search" id="submit"></button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="layui-col-md12 ">
                <div class="layui-card webinfo">
                    <div class="layui-card-header">
                        <i class="layui-icon layui-icon-app"></i>
                        <span>文章分类</span>
                    </div>
                    <div class="layui-card-body">
                        <ul>
                            {% if Categorys %}
                                {% for category in Categorys %}
                                    <a href="{% url 'MyBlog:category' category.id %}" title="{{ category.Name }}" id="link{{ category.id }}"><li>{%if category.Name|length >= 25 %}{{category.Name|slice:"25"}}...{%else%} {{category.Name}}{%endif%}</li></a>
                                {% endfor %}
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="layui-col-md12">
                <div class="layui-card ranker">
                    <div class="layui-card-header">
                        <i class="iconfont icon-wenzhang"></i>
                        <span>点击排行</span>
                    </div>
                    <div class="layui-card-body">
                        <ul>
                            {% if Rankers %}
                                {% for ranker in Rankers %}
                                    <li><a href="{% url 'MyBlog:details' ranker.id %}" title="{{ ranker.title }}">{%if ranker.title|length >= 25 %}{{ranker.title|slice:"25"}}...{%else%}{{ranker.title}}{%endif%}</a></li>
                                {% endfor %}
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="layui-col-md12">
                <div class="layui-card">
                    <div class="layui-card-header">
                        <i class="layui-icon layui-icon-note"></i>
                        <span>标签云</span>
                    </div>
                    <div class="layui-card-body note">
                        {% if Tags %}
                            {% for tag in Tags %}
                                <a href="{% url 'MyBlog:types' tag.id  %}">{{ tag.TypeName }}</a>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script src="{% static '/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static '/lib/LoadBlog.js' %}" data-id="type={{ type }}&method={{ method }}"></script>
{% endblock %}

MyBlog/templates/MyBlog/archive.html
{% extends 'MyBlog/base.html' %}
{% load static %}
{% block title%}
    <title>花花与风-归档</title>
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'common/css/iconfont.css' %}">
{% endblock %}
{% block nav %}
<div class="nav" id="nav">
 <div class="menu-btn">
      <div class="menu"></div>
    </div>
    <div class="item">
        <a class="navpic" href="../"><img src="{% static 'common/imgs/logo.png' %}"></a>
        <ul class="nav-horizontal">
            <li class="nav-item"><a href="../blog">博客</a></li>
{#            <li class="layui-nav-item"><a href="../picture">相册</a></li>#}
            <li class="nav-item"><a href="../weblink">友情链接</a></li>
            <li class="nav-item layui-this"><a href="../archive">归档</a></li>
            <li class="nav-item"><a href="../message">留言</a></li>
            <li class="nav-item "><a href="../about">关于</a></li>
        </ul>
        <ul class="nav-tree">
            <li class="nav-item"><a href="../blog">博客</a></li>
{#            <li class="layui-nav-item"><a href="../picture">相册</a></li>#}
            <li class="nav-item"><a href="../weblink">友情链接</a></li>
            <li class="nav-item  layui-this"><a href="../archive">归档</a></li>
            <li class="nav-item"><a href="../message">留言</a></li>
            <li class="nav-item"><a href="../about">关于</a></li>
        </ul>
    </div>
</div>
{% endblock %}
{% block fluid %}
    <div class="layui-col-sm12 HeadBack">
    <h2>每天的点点滴滴将生活汇聚成一条回忆的长河</h2>
    </div>
{% endblock %}
{% block container %}
    <div class="layui-col-md85">
        <div class="layui-card">
            <div class="layui-card-header">博客归档</div>
            <div class="timeboxpadding">
                <div class="timebox">
                    <ul class="event_year">
                        <li><label for="2023">2023</label></li>
                        <li><label for="2022">2022</label></li>
                        <li><label for="2021">2021</label></li>
                        <li><label for="2020">2020</label></li>
                        <li><label for="2019">2019</label></li>
                        <li class="current"><label for="2018">2018</label></li>
                        <li><label for="2017">2017</label></li>
                    </ul>
                    <ul class="event_list">
                    </ul>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="layui-col-md35" >
        <div class="layui-col-space15">
            <div class="layui-col-md12 ">
                <div class="layui-card webinfo">
                    <div class="layui-card-header">
                        <i class="layui-icon layui-icon-app"></i>
                        <span>文章分类</span>
                    </div>
                    <div class="layui-card-body">
                        <ul>
                            {% if Categorys %}
                                {% for category in Categorys %}
                                    <a href="{% url 'MyBlog:category' category.id %}" title="{{ category.Name }}" id="link{{ category.id }}"><li>{%if category.Name|length >= 25 %}{{category.Name|slice:"25"}}...{%else%} {{category.Name}}{%endif%}</li></a>
                                {% endfor %}
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="layui-col-md12">
                <div class="layui-card ranker">
                    <div class="layui-card-header">
                        <i class="iconfont icon-wenzhang"></i>
                        <span>点击排行</span>
                    </div>
                    <div class="layui-card-body">
                        <ul>
                            {% if Rankers %}
                                {% for ranker in Rankers %}
                                    <li><a href="{% url 'MyBlog:details' ranker.id %}" title="{{ ranker.title }}">{%if ranker.title|length >= 25 %}
                                        {{ranker.title|slice:"25"}}...
                                    {%else%} {{ranker.title}}
                                    {%endif%}</a></li>
                                {% endfor %}
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="layui-col-md12">
                <div class="layui-card">
                    <div class="layui-card-header">
                        <i class="layui-icon layui-icon-note"></i>
                        <span>标签云</span>
                    </div>
                    <div class="layui-card-body note">
                        {% if Tags %}
                            {% for tag in Tags %}
                                <a  href="{% url 'MyBlog:types' tag.id %}">{{ tag.TypeName }}</a>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script>
        $(function(){
            initData();
        });
        //加载初始化数据
        function initData(){
            $.ajax({
                type:'GET',
                dataType: "json",
                url:"../../loadarchivedata/",
                success:function(result){
                    {#alert("加载数据");#}
                    if(result.code=="0"){

                        var info = result.data;
                        console.log(info);
                        for(var i in info)
                        {
                            var details=""
                            var item=info[i].detail
                            for(var j in item){
                                details+=" <li><span>"+item[j].monthday+"</span><p><span><a href=\"../../details/"+item[j].id+"\">"+item[j].title+"</a></span></p></li>"
                            }
                            var str=""
                            str+="<div><h3 id=\""+info[i].year+"\">"+info[i].year+"</h3>"+details+"</div>"
                            console.log(str);
                            $(".event_list").append(str)
                        }
                    }else{
                        alert("数据错误！请联系管理员");
                    }
                },
                error:function(){
                    alert("发生错误");
                }
            });
        }
    </script>
    <script>
        $(function(){
            $('label').click(function(){
                $('.event_year>li').removeClass('current');
                $(this).parent('li').addClass('current');
                var year = $(this).attr('for');
                $('#'+year).parent().prevAll('div').slideUp(800);
                $('#'+year).parent().slideDown(800).nextAll('div').slideDown(800);
            });
        });
    </script>
{% endblock %}

MyBlog/templates/MyBlog/message.html
{% extends 'MyBlog/base.html' %}
{% load static %}
{% block title%}
    <title>花花与风-欢迎留言</title>
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'common/css/paging.css' %}">
    <link rel="stylesheet" href="{% static 'common/css/iconfont.css' %}">
{% endblock %}
{% block nav %}
    <div class="nav" id="nav">
        <div class="menu-btn">
            <div class="menu"></div>
        </div>
        <div class="item">
            <a class="navpic" href="../"><img src="{% static 'common/imgs/logo.png' %}"></a>
            <ul class="nav-horizontal">
                <li class="nav-item"><a href="../blog">博客</a></li>
                {#            <li class="layui-nav-item"><a href="../picture">相册</a></li>#}
                <li class="nav-item"><a href="../weblink">友情链接</a></li>
                <li class="nav-item"><a href="../archive">归档</a></li>
                <li class="nav-item  layui-this"><a href="../message">留言</a></li>
                <li class="nav-item"><a href="../about">关于</a></li>
            </ul>
            <ul class="nav-tree">
                <li class="nav-item"><a href="../blog">博客</a></li>
                {#            <li class="layui-nav-item"><a href="../picture">相册</a></li>#}
                <li class="nav-item"><a href="../weblink">友情链接</a></li>
                <li class="nav-item"><a href="../archive">归档</a></li>
                <li class="nav-item  layui-this"><a href="../message">留言</a></li>
                <li class="nav-item"><a href="../about">关于</a></li>
            </ul>
        </div>
    </div>
{% endblock %}
{% block fluid %}
    <div class="layui-col-sm12 HeadBack">
        <h2>既然来了就留下点什么吧</h2>
    </div>
{% endblock %}
{% block container %}
    <div class="layui-col-md85">
        <div class="layui-card">
            <div class="layui-card-body">
                <form class="layui-form message-con" method="post">
                    {% csrf_token %}
                    <div class="layui-form-item Message-input">
                        <div class="layui-inline">
                            <div class="layui-input-inline input-icon">
                                <input type="tel" name="username" lay-verify="" autocomplete="off" class="layui-input username" placeholder="昵称（必填）">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <div class="layui-input-inline input-icon">
                                <input type="text" name="email" lay-verify="" autocomplete="off" class="layui-input email" placeholder="邮箱（必填）">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <div class="layui-input-inline input-icon">
                                <input type="text" name="website" lay-verify="" autocomplete="off" class="layui-input website" placeholder="站点">
                            </div>
                        </div>
                    </div>
                    <div class="layui-form-item ">
                        <textarea class="layui-textarea" id="MessageCon" placeholder="说点什么"></textarea>
                    </div>
                    <div class="layui-form-item mybtn">
                        <button class="layui-btn layui-btn-green" type="button" id="submit">留言</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="layui-card">
            <div class="layui-card-header">最新留言</div>
            <div id="messagecon">
            </div>
            <div id="pagination"></div>
        </div>
    </div>
    <div  class="layui-col-md35" >
        <div class="content-sapce-15">
            <div class="layui-col-md12 ">
                <div class="layui-card webinfo">
                    <div class="layui-card-header">
                        <i class="layui-icon layui-icon-app"></i>
                        <span>文章分类</span>
                    </div>
                    <div class="layui-card-body">
                        <ul>
                            {% if Categorys %}
                                {% for category in Categorys %}
                                    <a href="{% url 'MyBlog:category' category.id %}" title="{{ category.Name }}" id="link{{ category.id }}"><li>{%if category.Name|length >= 25 %}{{category.Name|slice:"25"}}...{%else%} {{category.Name}}{%endif%}</li></a>
                                {% endfor %}
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="layui-col-md12">
                <div class="layui-card ranker">
                    <div class="layui-card-header">
                        <i class="iconfont icon-wenzhang"></i>
                        <span>点击排行</span>
                    </div>
                    <div class="layui-card-body">
                        <ul>
                            {% if Rankers %}
                                {% for ranker in Rankers %}
                                    <li><a href="{% url 'MyBlog:details' ranker.id %}" title="{{ ranker.title }}">{%if ranker.title|length >= 25 %}{{ranker.title|slice:"25"}}...{%else%}{{ranker.title}}{%endif%}</a></li>
                                {% endfor %}
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="layui-col-md12">
                <div class="layui-card">
                    <div class="layui-card-header">
                        <i class="layui-icon layui-icon-note"></i>
                        <span>标签云</span>
                    </div>
                    <div class="layui-card-body note">
                        {% if Tags %}
                            {% for tag in Tags %}
                                <a href="{% url 'MyBlog:types' tag.id  %}">{{ tag.TypeName }}</a>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script src="{% static '/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static '/common/js/paging.js' %}"></script>
    <script src="{% static '/common/js/jquery.timeago.js' %}" ></script>
    <script src="{% static '/lib/loadMessage.js' %}" ></script>
{% endblock %}