MyBlog/urls.py
from django.urls import path

from . import views
app_name = 'MyBlog'
urlpatterns = [
    path('', views.index, name='index'),
    path('blog/', views.Blog, name='Blog'),
    path('loadblog', views.loadblog, name='loadblog'),
    path('admin/menushow/', views.menushow, name='menushow'),
    path('admin/', views.admin, name='admin'),
    path('admin/login/', views.login, name='login'),
    path('admin/console/', views.console, name='console'),
    path('message/', views.message, name='message'),
    path('loadmessage/', views.loadmessage, name='loadmessage'),
    path('submitmessage/', views.submitmessage, name='submitmessage'),
    path('picture/', views.picture, name='picture'),
    path('archive/', views.archive, name='archive'),
    path('like/', views.like, name='like'),
    path('search/', views.search, name='search'),
    path('replylike/', views.replylike, name='replylike'),
    path('about/', views.about, name='about'),
    path('test/', views.test, name='test'),
    path('details/<int:id>', views.details, name='details'),
    path('weblink/', views.weblink, name='weblink'),
    path('picdetails/<int:id>', views.picdetails, name='picdetails'),
    path('types/<int:type>', views.types, name='types'),
    path('category/<int:type>', views.category, name='category'),
    path('imgtypes/<str:type>', views.imgtypes, name='imgtypes'),
    path('commentdata/', views.commentdata, name='commentdata'),
    path('commenttocommentdata/', views.commenttocommentdata, name='commenttocommentdata'),
    path('commenttoreplydata/', views.commenttoreplydata, name='commenttoreplydata'),
    path('loadcommentdata/', views.loadcommentdata, name='loadcommentdata'),
    path('loadarchivedata/', views.loadarchivedata, name='loadarchivedata'),
    path('replydata/', views.replydata, name='replydata'),
    path('replytomessage/', views.replytomessage, name='replytomessage'),
    path('replytoreply/', views.replytoreply, name='replytoreply'),
    path('admin/Top/', views.Top, name='Top'),
    path('admin/upload_ajax/', views.upload_ajax, name='upload_ajax'),
    path('admin/editblog/', views.editblog, name='editblog'),
    path('admin/deleteblog/', views.deleteblog, name='deleteblog'),
    path('admin/Blogsdata/', views.Blogsdata, name='Blogsdata'),
    path('admin/BlogEdit/', views.BlogEdit, name='BlogEdit'),
    path('admin/PicEdit/', views.PicEdit, name='PicEdit'),
    path('admin/PicUploads/', views.PicUploads, name='PicUploads'),
    path('admin/PictureManage/', views.PictureManage, name='PictureManage'),
    path('admin/PicDetailManage/<int:id>', views.PicDetailManage, name='PicDetailManage'),
    path('admin/setWrap/', views.setWrap, name='setWrap'),
    path('admin/userinfo/<int:userid>/', views.userinfo, name='userinfo'),
    path('admin/password/<int:userid>/', views.password, name='password'),
    # path('admin/password/<int:userid>/', views.password, name='password'),



]

MyBlogWeb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', include('MyBlog.urls')),
    path("favicon.ico", RedirectView.as_view(url='static/favicon.ico')),
    path('adminht/', admin.site.urls),
    path('ueditor/', include('DjangoUeditor.urls' )),


]

MyBlog/models.py
from django.db import connection, models
from django.db.models.fields.files import ImageFieldFile
from PIL import Image
from MyBlogWeb.settings import MEDIA_ROOT
import os, datetime, uuid
import re
from DjangoUeditor.models import UEditorField


class BlogManager(models.Manager):
    def blogSet(self):
        cursor = connection.cursor()
        cursor.execute("""
            SELECT *
            FROM Blog
            """)
        return [row for row in cursor.fetchall()]

class Blog(models.Model):
    id = models.AutoField(db_column='id', primary_key=True)
    title = models.CharField(db_column='Title', max_length=50, blank=True, null=True)  # Field name made lowercase.
    abstract=models.CharField(db_column='abstract', max_length=300, blank=True, null=True)
    createdate = models.DateTimeField(db_column='createdate', blank=True, null=True)  # Field name made lowercase.
    modifydate=models.DateTimeField(db_column='modifydate', blank=True, null=True)
    author = models.CharField(db_column='Author', max_length=50, blank=True, null=True)  # Field name made lowercase.
    blogcontent = UEditorField(db_column='blogcontent',verbose_name='内容',width=600, height=300, toolbars="full", imagePath="images/upload/%(datetime)s_%(rnd)s.%(extname)s", filePath="file/upload/%(datetime)s_%(rnd)s.%(extname)s", upload_settings={"imageMaxSize":1204000},
             settings={},command=None,blank=True)  #
    hit = models.IntegerField(db_column='hit', blank=True, null=True)
    isTop = models.IntegerField(db_column='isTop', blank=True, null=True)
    isorg = models.IntegerField(db_column='isorg', blank=True, null=True)
    type = models.IntegerField(db_column='Type',blank=True, null=True)
    imgTitle = models.CharField(db_column='imgTitle', max_length=50, blank=True, null=True)  # Field name made lowercase.
    Category = models.CharField(db_column='Category', max_length=50, blank=True,null=True)  # Field name made lowercase.
    year = models.CharField(db_column='year', max_length=4, blank=True,
                                null=True)  # Field name made lowercase.
    month = models.CharField(db_column='month', max_length=2, blank=True,
                                null=True)  # Field name made lowercase.
    day = models.CharField(db_column='day', max_length=2, blank=True,
                                null=True)  # Field name made lowercase.
    blog_blogtype = models.ManyToManyField(to="BlogType",
                                     through="BlogTypeRelation",
                                     through_fields=("Blog", "BlogType"))
    blog_CategoryToBlog = models.ManyToManyField(to="Category",
                                           through="CategoryToBlog",
                                           through_fields=("Blog", "Category"))
    objects = models.Manager()
    blog_objects = BlogManager()

    def __str__(self):
        dr = re.compile(r'<[^>]+>',re.S)
        dd = dr.sub('', self.blogcontent)
        if len(dd)>500:
            return '{0}...'.format(dd[0:499])
        else:
            return '{0}...'.format(dd)

    class Meta:
        managed = False
        db_table = 'Blog'

class UserManager(models.Manager):
    def userSet(self):
        cursor = connection.cursor()
        cursor.execute("""
            SELECT *
            FROM Users
            """)
        return [row for row in cursor.fetchall()]

class Users(models.Model):
    userid = models.AutoField(db_column='userid', primary_key=True)  # Field name made lowercase.
    useraccount = models.CharField(db_column='useraccount', max_length=50, blank=True,
                                   null=True)  # Field name made lowercase.
    userpassword = models.CharField(db_column='userpassword', max_length=50, blank=True,
                                    null=True)  # Field name made lowercase.
    username = models.CharField(db_column='username', max_length=200, blank=True,
                                null=True)  # Field name made lowercase.
    website = models.CharField(db_column='website', max_length=50, blank=True, null=True)  # Field name made lowercase.
    type = models.IntegerField(db_column='type', blank=True, null=True)
    email = models.CharField(db_column='email', max_length=200, blank=True, null=True)  # Field name made lowercase.
    userpic = models.CharField(db_column='userpic', max_length=50, blank=True, null=True)  # Field name made lowercase.
    objects = models.Manager()
    user_objects = UserManager()

    class Meta:
        managed = False
        db_table = 'Users'

class BlogTypeManager(models.Manager):
    def blogtypeSet(self):
        cursor = connection.cursor()
        cursor.execute("""
            SELECT *
            FROM BlogType
            """)
        return [row for row in cursor.fetchall()]

class BlogType(models.Model):
    id = models.AutoField(db_column='id', primary_key=True)
    TypeName = models.CharField(db_column='TypeName', max_length=50, blank=True, null=True)  # Field name made lowercase.
    category=models.IntegerField(db_column='category',blank=True, null=True)
    objects = models.Manager()
    blogtype_objects = BlogTypeManager()
    blogtype_blog= models.ManyToManyField(to="Blog",
                                           through="BlogTypeRelation",
                                           through_fields=("BlogType", "Blog"))
    pictype_pic = models.ManyToManyField(to="PicManage",
                                           through="PicTypeRelation",
                                           through_fields=("type", "pictureManage"))
    class Meta:
        managed = False
        db_table = 'BlogType'

class BlogTypeRelation(models.Model):
    id = models.AutoField(db_column='id', primary_key=True)
    Blog = models.ForeignKey(to="Blog",to_field="id",on_delete=models.CASCADE)
    BlogType = models.ForeignKey(to="BlogType",to_field="id",on_delete=models.CASCADE)

    class Meta:
        managed = False
        db_table = 'BlogTypeRelation'
        unique_together=("Blog","BlogType")

class PicTypeRelation(models.Model):
    id = models.AutoField(db_column='id', primary_key=True)
    pictureManage = models.ForeignKey(to="PicManage",to_field="id",on_delete=models.CASCADE)
    type = models.ForeignKey(to="BlogType",to_field="id",on_delete=models.CASCADE)
    # objects = models.Manager()
    # blogtyperelation_objects = BlogTypeRelationManager()

    class Meta:
        managed = False
        db_table = 'PicTypeRelation'
        unique_together=("pictureManage","type")

class PictureManager(models.Manager):
    def pictureSet(self):
        cursor = connection.cursor()
        cursor.execute("""
            SELECT *
            FROM BlogType
            """)
        return [row for row in cursor.fetchall()]

class Picture(models.Model):
    id = models.AutoField(db_column='id', primary_key=True)
    pic = models.ForeignKey(to="PicManage", to_field="id", on_delete=models.CASCADE)
    picdesc = models.CharField(db_column='picdesc', max_length=200, blank=True, null=True)  # Field name made lowercase.
    url = models.CharField(db_column='url',max_length=50, blank=True)  # Field name made lowercase.
    objects = models.Manager()
    picture_objects = PictureManager()

    class Meta:
        managed = False
        db_table = 'Picture'

class PicManageManager(models.Manager):
    def picManagetureSet(self):
        cursor = connection.cursor()
        cursor.execute("""
            SELECT *
            FROM PicManage
            """)
        return [row for row in cursor.fetchall()]

# 创建原始图片名称
def generate_filename(instance, filename):
    """
    安全考虑，生成随机文件名
    """
    directory_name = datetime.datetime.now().strftime('upload/imgs/%Y/%m')
    filename = uuid.uuid4().hex + os.path.splitext(filename)[-1]
    return os.path.join(directory_name, filename)

# 创建缩略图名称
def generate_filename_thumb(instance, filename):
    directory_name = datetime.datetime.now().strftime('upload/thumb/%Y/%m')
    filename = uuid.uuid4().hex + os.path.splitext(filename)[-1]
    return os.path.join(directory_name, filename)

# 制作缩略图

UPLOAD_ROOT = generate_filename
THUMB_ROOT = "upload/thumb/" # 这个是最终的缩略图要保存的路径
def make_thumb(path, size = 800):
    pixbuf = Image.open(path)
    width, height = pixbuf.size

    if width > size:
        delta = width / size
        height = int(height / delta)
        pixbuf.thumbnail((size, height), Image.ANTIALIAS)
        return pixbuf



class PicManage(models.Model):
    id = models.AutoField(db_column='id', primary_key=True)
    title = models.CharField(db_column='title', max_length=50, blank=True, null=True)  # Field name made lowercase.
    picdesc = models.CharField(db_column='picdesc', max_length=200, blank=True, null=True)  # Field name made lowercase.
    # 商品图片
    img = models.ImageField(upload_to=generate_filename, null=True)
    # 商品缩略图
    imgthumb = models.ImageField(upload_to=generate_filename_thumb, null=True)
    # url = models.CharField(db_column='url', max_length=50, blank=True, null=True)  # Field name made lowercase.
    author = models.CharField(db_column='author', max_length=50, blank=True, null=True)  # Field name made lowercase.
    createdate = models.DateTimeField(db_column='createdate', blank=True, null=True)  # Field name made lowercase.
    modifydate = models.DateTimeField(db_column='modifydate',  blank=True, null=True)  # Field name made lowercase.
    # type = models.IntegerField(db_column='type',blank=True, null=True)  # Field name made lowercase.
    pic_pictype = models.ManyToManyField(to="BlogType",
                                           through="PicTypeRelation",
                                           through_fields=("pictureManage", "type"))
    objects = models.Manager()
    picmanage_objects = PicManageManager()

    class Meta:
        managed = False
        db_table = 'PicManage'

    def save(self):
        super(PicManage, self).save()  # 将上传的图片先保存一下，否则报错

MyBlog/templates/MyBlogAdmin/Blog.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>layuiAdmin 网站用户</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    {% load static %}
    <link rel="stylesheet" href="{% static '/layui/css/layui.css' %}" media="all">
    <link rel="stylesheet" href="{% static '/layui/css/public.css' %}" media="all">
</head>
<body class="childrenBody" style="background-color: #FFFFFF">
<form class="layui-form">
	<blockquote class="layui-elem-quote quoteBox">
		<form class="layui-form">
			<div class="layui-inline">
				<div class="layui-input-inline">
					<input type="text" class="layui-input searchVal" placeholder="请输入搜索的内容" />
				</div>
				<a class="layui-btn search_btn" data-type="reload">搜索</a>
			</div>
			<div class="layui-inline">
				<a class="layui-btn layui-btn-normal addNews_btn">添加文章</a>
			</div>
			<div class="layui-inline">
				<a class="layui-btn layui-btn-danger layui-btn-normal delAll_btn">批量删除</a>
			</div>
		</form>
	</blockquote>
	<table id="test-table-toolbar" lay-filter="test-table-toolbar"></table>
	<!--审核状态-->


	<!--操作-->
<script type="text/html" id="test-table-toolbar-barDemo">
                <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" ><i class="layui-icon layui-icon-edit"></i>编辑</a>
                <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del"><i class="layui-icon layui-icon-delete"></i>删除</a>
            </script>
</form>
<script src="{% static '/layui/layui.js' %}"></script>
<script src="{% static '/lib/Newlist.js' %}"></script>
</body>
</html>

MyBlog/templates/MyBlogAdmin/PicdetailMan.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>layuiAdmin 网站用户</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    {% load static %}
    <link rel="stylesheet" href="{% static '/layui/css/layui.css' %}" media="all">
    <link rel="stylesheet" href="{% static '/layui/css/modules/layer/default/layer.css' %}" media="all">
    <link rel="stylesheet" href="{% static '/layui/css/public.css' %}" media="all">
    <link rel="stylesheet" href="{% static '/css/../../static/common/imgs/blog.css' %}" media="all">
    <link rel="stylesheet" href="{% static '/zjupload/control/css/zyUpload.css' %}" type="text/css">
    <script src="{% static '/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static '/zjupload/control/js/zyUpload.js' %}"></script>
    <script src="{% static '/zjupload/core/zyFile.js' %}"></script>
    <script src="{% static '/zjupload/demo.js' %}"></script>
</head>
<body class="childrenBody" style="background-color: #FFFFFF">
{#<form class="layui-form">#}
{# {% csrf_token %}#}
<div class="layui-fluid ">
    <div class="layui-col-sm12">
        <div class="layui-card">
            <div class="layui-card-body">
                <h1 style="text-align:center;">图片上传</h1>
                <div id="demo" class="demo"></div>
            </div>
        </div>
    </div>
    <div class="layui-col-sm12">
        <div class="layui-row  layui-col-space15">
            {% if PicManages.picture_set.all %}
                {% for i in PicManages.picture_set.all %}
                    <div class="layui-col-md2">
                        <div class="picbox" id="picboxtag{{ i.id }}" style="background-image: url({{  i.url }})">
                            <div class="pic-function" id="pic-functiontag{{ i.id }}">
                                <ul>
                                    <li><button type="button" class="picbtn1">替换</button></li>
                                    <li><button type="button" class="picbtn2">删除</button></li>
                                    <li><button type="button" class="picbtn3">设置为封面</button></li>
                                </ul>
                            </div>
                        </div>
                        <div class="layui-card">
                            <div class="layui-card-body">
                                <input class="layui-input" placeholder="请输入描述信息">
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>

    </div>
    <div class="layui-col-sm12" style="margin-top: 15px;">
        <div class="layui-row">
            <div class="layui-card">
                <div class="layui-card-body">
                    <button class="layui-btn layui-btn-primary" type="button">修改</button>
                </div>
            </div>
        </div>
    </div>
</div>
{#</form>#}
<script src="{% static '/layui/layui.js' %}"></script>
<script src="{% static '/layui/lay/modules/layer.js' %}"></script>
{#<script src="{% static '/js/jquery-3.3.1.min.js' %}"></script>#}
<script>
    var id=''
    $("[id^=picboxtag]").hover(function() {
        id = $(this).attr("id").split("picboxtag")[1]
        funcid = 'pic-functiontag' + id
        $("#" + funcid).css('display', 'block')
    },function(){
        id=$(this).attr("id").split("picboxtag")[1]
        funcid='pic-functiontag'+id
        $("#"+funcid).css('display','none')
    });
    $("[id^=picboxtag]").children().children().children().children(".picbtn1").hover(function() {
        $(this).addClass("layui-btn")
        console.log(this)
    },function () {
        $(this).removeClass("layui-btn")
        console.log(this)
    });
    $("[id^=picboxtag]").children().children().children().children(".picbtn2").hover(function() {
        $(this).addClass("layui-btn")
        console.log(this)
    },function () {
        $(this).removeClass("layui-btn")
        console.log(this)
    });
    $("[id^=picboxtag]").children().children().children().children(".picbtn3").hover(function() {
        $(this).addClass("layui-btn")
        $(this).click(function () {
            $.ajax({
                type:"GET",
                data: {'picid':id,
                    {#"csrfmiddlewaretoken":$("[name='csrfmiddlewaretoken']").val(),#}
                },
                url: "{% url 'MyBlog:setWrap' %}", //后台处理函数的url
                cache: false,
                {#headers:{csrfmiddlewaretoken:$('[name="csrfmiddlewaretoken"]').val()},#}
                contentType: "application/json",
                success: function(result) {
                    {#var dataobj=JSON.parse(result);#}
                    {#console.log('OK111')#}
                    layer.msg(result.message);
                },
            });
        })
        console.log(this)
    },function () {
        $(this).removeClass("layui-btn")
        console.log(this)
    });
</script>
</body>
</html>

MyBlog/templates/MyBlogAdmin/PictureManage.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>layuiAdmin 网站用户</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    {% load static %}
    <link rel="stylesheet" href="{% static '/layui/css/layui.css' %}" media="all">
    <link rel="stylesheet" href="{% static '/layui/css/public.css' %}" media="all">
    <link rel="stylesheet" href="{% static '/css/../../static/common/imgs/blog.css' %}" media="all">
</head>
<body class="childrenBody" style="background-color: #FFFFFF">
<form class="layui-form">
    <div class="layui-fluid">
        <div class="layui-col-sm12">
            <div class="layui-card">
                <div class="layui-card-body">
                    <button class="layui-btn layui-btn-normal addNews_btn">新增相册</button>
                </div>
            </div>
        </div>
        <div class="layui-col-sm12">
            <div class="layui-card">
                <div class="layui-card-body">
                    <div class="layui-row layui-col-space15">
                        {% if PicManages %}
                            {% for i in PicManages %}
                                <div class="layui-col-md2">
                                    <a href="{% url 'MyBlog:PicDetailManage' i.id %}">

                                        <div class="box" style="background-image: url(/static/media/{{  i.imgthumb }})">
                                            <div class="box-content">
                                                <h5 class="title">{{ i.title }}</h5>
                                                <span class="post">{{ i.picdesc }}</span>
                                            </div>
                                            <div class="picdesc"><span>by {{ i.author }}</span> <span>{{ i.picture_set.count  }} 张</span><p>{{ i.createdate|date:"Y-m-d"  }}</p>
                                            </div>

                                        </div>

                                    </a>
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script src="{% static '/layui/layui.js' %}"></script>

</body>
</html>

MyBlog/templates/MyBlogAdmin/addrole.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>权限设置</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    {% load static %}
    <link rel="stylesheet" href="{% static '/layui/css/layui.css' %}">
    {#     <link rel="stylesheet" href="{% static '/layui/css/admin.css' %}">#}
</head>
<body>
    <div class="layui-form" lay-filter="layuiadmin-form-useradmin" id="layuiadmin-form-useradmin" style="padding: 20px 0 0 0;">
        <div class="layui-form-item">
            <label class="layui-form-label">角色名</label>
            <div class="layui-input-inline">
                <input type="text" name="rolename" value="{{ roles.rolename }}" lay-verify="required" placeholder="请输入角色名" autocomplete="off" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">数据可见</label>
            <div class="layui-input-inline">
                <select name="queryrange" lay-verify="required">
                    {% if roles %}
                    <option  value="{{ roles.queryrange }}" >{% if roles.queryrange == '99' %}全部{% else %}{{ roles.queryrange }}{% endif %}</option>
                    {% else %}
                        <option  value="99" >全部</option>
                    {% endif %}
                </select>
            </div>

        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">电话导出</label>
            <div class="layui-input-inline">
                <select name="canseephone" lay-verify="required">
                    {% if roles %}
                    <option  value="{{ roles.canseephone }}" >{{ roles.canseephone }}</option>
                     {% else %}
                        <option  value="导出可见" >导出可见</option>
                    {% endif %}
                </select>
            </div>

        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">备注</label>
            <div class="layui-input-inline">
                <textarea name="RoleDesc" lay-verify="" style="width: 300px; height: 150px;" autocomplete="off" class="layui-textarea" >{{ roles.roledesc }}</textarea>
            </div>
        </div>
        <div class="layui-form-item layui-hide">
            <input type="button" lay-submit lay-filter="LAY-user-role-submit" id="LAY-user-role-submit"  value="确认">
        </div>
    </div>
<script src="{% static '/layui/layui.js' %}"></script>

<script>
    layui.config({
        base: '{% static '/' %}' //静态资源所在路径
    }).extend({
        index: 'lib/index' //主入口模块
    }).use(['index', 'form', 'upload'], function(){
        var $ = layui.$
            ,form = layui.form
    })
</script>
</body>
</html>

MyBlog/templates/MyBlogAdmin/console.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
</head>
<style type="text/css">

body {
background-image:url({% static 'common/imgs/index.png' %});
background-position: center;
background-repeat: no-repeat;
background-attachment: fixed;
background-color: #ffffff;
}

</style>
<body>

</body>
</html>

MyBlog/templates/MyBlogAdmin/pictureEdit.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>由html5实现的文件上传预览功能</title>
    {% load static %}
    <link rel="stylesheet" href="{% static '/layui/css/layui.css' %}" media="all">
    <link rel="stylesheet" href="{% static '/layui/css/modules/layer/default/layer.css' %}" media="all">
    <link rel="stylesheet" href="{% static '/layui/css/public.css' %}" media="all">
    <link rel="stylesheet" href="{% static '/css/../../static/common/imgs/blog.css' %}" media="all">
    <link rel="stylesheet" href="{% static 'zjupload/control/css/zyUpload.css' %}" type="text/css">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>

    <script src="{% static 'zjupload/control/js/zyUpload.js' %}"></script>

    <script src="{% static 'zjupload/core/zyFile.js' %}"></script>
    <script src="{% static 'zjupload/demo.js' %}"></script>
</head>
<body class="childrenBody" style="background-color: #FFFFFF">
<div class="layui-fluid ">
    <div class="layui-col-sm12">
        <div class="layui-card">
            <div class="layui-card-body">
                <h1 style="text-align:center;">图片上传</h1>
                <div id="demo" class="demo"></div>
            </div>
        </div>
    </div>
    <div class="layui-col-sm12">
        <div class="layui-row  layui-col-space15">
            {% if PicManages.picture_set.all %}
                {% for i in PicManages.picture_set.all %}
                    <div class="layui-col-md2">
                        <div class="picbox" id="picboxtag{{ i.id }}" style="background-image: url({{  i.url }})">
                            <div class="pic-function" id="pic-functiontag{{ i.id }}">
                                <ul>
                                    <li><button type="button" class="picbtn1">替换</button></li>
                                    <li><button type="button" class="picbtn2">删除</button></li>
                                    <li><button type="button" class="picbtn3">设置为封面</button></li>
                                </ul>
                            </div>
                        </div>
                        <div class="layui-card">
                            <div class="layui-card-body">
                                <input class="layui-input" placeholder="请输入描述信息">
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>

    </div>
    <div class="layui-col-sm12" style="margin-top: 15px;">
        <div class="layui-row">
            <div class="layui-card">
                <div class="layui-card-body">
                    <button class="layui-btn layui-btn-primary" type="button">修改</button>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>